# Generated by Django 2.2.6 on 2022-04-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220410_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
